# Generated by cpp11: do not edit by hand

ks_stat_presort <- function(joint, labs, power, na) {
  .Call(`_twosamples_ks_stat_presort`, joint, labs, power, na)
}

kuiper_stat_presort <- function(joint, labs, power, na) {
  .Call(`_twosamples_kuiper_stat_presort`, joint, labs, power, na)
}

cvm_stat_presort <- function(joint, labs, power, na) {
  .Call(`_twosamples_cvm_stat_presort`, joint, labs, power, na)
}

ad_stat_presort <- function(joint, labs, power, na) {
  .Call(`_twosamples_ad_stat_presort`, joint, labs, power, na)
}

wass_stat_presort <- function(joint, labs, power, na) {
  .Call(`_twosamples_wass_stat_presort`, joint, labs, power, na)
}

dts_stat_presort <- function(joint, labs, power, na) {
  .Call(`_twosamples_dts_stat_presort`, joint, labs, power, na)
}
