# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ks_stat_presort <- function(joint, labs, power = 1.0, na = 0.0) {
    .Call(`_twosamples_ks_stat_presort`, joint, labs, power, na)
}

kuiper_stat_presort <- function(joint, labs, power = 1.0, na = 0.0) {
    .Call(`_twosamples_kuiper_stat_presort`, joint, labs, power, na)
}

cvm_stat_presort <- function(joint, labs, power = 2.0, na = 0.0) {
    .Call(`_twosamples_cvm_stat_presort`, joint, labs, power, na)
}

ad_stat_presort <- function(joint, labs, power = 1.0, na = 0.0) {
    .Call(`_twosamples_ad_stat_presort`, joint, labs, power, na)
}

wass_stat_presort <- function(joint, labs, power = 1.0, na = 0.0) {
    .Call(`_twosamples_wass_stat_presort`, joint, labs, power, na)
}

dts_stat_presort <- function(joint, labs, power = 1.0, na = 0.0) {
    .Call(`_twosamples_dts_stat_presort`, joint, labs, power, na)
}

